# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run :
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Build project
          command: ./gradlew build

